### PR TITLE
Added support for returning the last state of an observable.

### PR DESCRIPTION
**Pull request by shannonmoeller**
Tried to keep it minimal and framework agnostic. Tests passed without change (only dropped the `.skip`).

### CODE REVIEW

**Comment by phated** [comment]
That's a neat trick for storing the next value.  Do you have a use case for this functionality?

**Comment by shannonmoeller** [comment]
I've written a [`map-stream`](http://npm.im/map-stream) implementation where `async-done` is used to resolve the mapping function. This allows transform stream authors to choose whatever async pattern suits their fancy:

https://github.com/shannonmoeller/async-map-stream/blob/master/test/asyncMapStream.spec.js#L29-L54

**Comment by phated** [comment]
That's awesome.  Merging :100:

**Comment by shannonmoeller** [comment]
Thank you, sir!

**Comment by phated** [comment]
Published as 1.2.0 - Thanks for the awesome implementation

**Comment by tunnckoCore** [comment]
Cool. What I did was detecting `ret.value` instead of `.state` from `onNext`. 
Is it better or? Thoughts?

for example: [few lines from `letta-value`](https://github.com/hybridables/letta-value/blob/master/index.js#L16-L23) and tests [are currently in always-done](https://github.com/hybridables/always-done/blob/master/test/observables.js)

**Comment by shannonmoeller** [comment]
@tunnckoCore I'm not sure what you mean. I only used `onNext.state` as a convenient place to store a value that is specific to the observable use case. Could have stored it in a scope variable, but I liked how this kept things tidy.

**Comment by tunnckoCore** [comment]
@shannonmoeller nevermind. I'm just saying that i think this thing can be done like that

```js
   if(result && typeof result.subscribe === 'function'){
      if (result.value) return done(null, result.value)
      // assume RxJS observable
      result.subscribe(noop, onError, onSuccess);
      return;
    }
```

Nevermind :) Both ways seems to work.

**Comment by shannonmoeller** [comment]
@tunnckoCore Using `result.value` in that way would only work with truthy values, but storing the latest value received by the onNext handler is guaranteed to be the right thing.

Also, is `.value` a standard observable thing? I can't find any documentation on it.

**Comment by tunnckoCore** [comment]
> in that way would only work with truthy values

haha, good catch, i should fix it.

> I can't find any documentation on it.

Same here. I just noticed that it is the thing that is needed.

> Also, is .value a standard observable thing?

I'm not sure, I'm not familiar with RX.

**Pull request merged**
